data:
  train_ir_dataset_paths:
    - data/baseline-runs/colbert/msmarco-passage-train-judged.run
  truncate: true
  max_length: 256
  batch_size: 16
  val_batch_size: 10
  predict_batch_size: 1
  train_sample_size: 8
  train_sample_depth: 200
  depth: 100
  num_relevant_samples: 1
  min_num_relevant_samples: 0
  shuffle_queries: true
  shuffle_docs: false
  relevant_sampling_strategy: random
  non_relevant_sampling_strategy: random
  num_workers: 2
