data:
  class_path: LightningIRDataModule
  init_args:
    num_workers: 4
    train_batch_size: 4
    inference_batch_size: 4
    train_dataset:
      class_path: RunDataset
      init_args:
        run_path: data/baseline-runs/colbert/msmarco-passage-train-judged.parquet
        targets: relevance
        depth: 200
        sample_size: 8
        sampling_strategy: single_relevant
    inference_datasets:
      - class_path: RunDataset
        init_args:
          run_path: data/baseline-runs/bm25/msmarco-passage-v2-trec-dl-2021-judged.run
          targets: relevance
          depth: 100
          sample_size: 100
          sampling_strategy: top
      - class_path: RunDataset
        init_args:
          run_path: data/baseline-runs/bm25/msmarco-passage-v2-trec-dl-2022-judged.run
          targets: relevance
          depth: 100
          sample_size: 100
          sampling_strategy: top
