data:
  class_path: LightningIRDataModule
  init_args:
    num_workers: 4
    train_batch_size: 1
    inference_batch_size: 4
    train_dataset:
      class_path: RunDataset
      init_args:
        run_path: __colbert-10000-sampled-100__msmarco-passage-train-judged.run
        targets: rank
        depth: 100
        sample_size: 100
        sampling_strategy: top
    