seed_everything: 42
trainer:
  precision: bf16-mixed
  max_steps: 20000
data:
  class_path: LightningIRDataModule
  init_args:
    train_batch_size: 32
    train_dataset:
      class_path: TupleDataset
      init_args:
        tuples_dataset: task2-collie-2025
model:
  class_path: set_encoder.module.SetEncoderModule
  init_args:
    model_name_or_path: google/electra-base-discriminator
    # model_name_or_path: google/electra-large-discriminator
    config:
      class_path: SetEncoderConfig
      init_args:
        query_length: 32
        doc_length: 256
        depth: 100
        add_extra_token: true
        sample_missing_docs: true
    loss_functions:
      - class_path: InfoNCE
      - class_path: set_encoder.loss.RepeatCrossEntropyLoss
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-05