seed_everything: 42
trainer:
  precision: bf16-mixed
  max_steps: 20000
data:
  class_path: LightningIRDataModule
  init_args:
    num_workers: 4
    train_batch_size: 32
    train_dataset:
      class_path: set_encoder.data.RepeatRunDataset
      init_args:
        run_path_or_id: task2-collie-2025
        targets: relevance
        depth: 200
        sample_size: 8
        sampling_strategy: single_relevant
        add_docs_not_in_ranking: true
model:
  class_path: set_encoder.module.SetEncoderModule
  init_args:
    model_name_or_path: google/electra-base-discriminator
    # model_name_or_path: google/electra-large-discriminator
    config:
      class_path: SetEncoderConfig
      init_args:
        query_length: 32
        doc_length: 256
        depth: 100
        add_extra_token: true
        sample_missing_docs: true
    loss_functions:
      - class_path: InfoNCE
      - class_path: set_encoder.loss.RepeatCrossEntropyLoss
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-05