trainer:
  precision: bf16-mixed
  logger: false
  enable_checkpointing: false
  callbacks:
  - class_path: set_encoder.data.RegisterRankDistiLLMNovelty
data:
  class_path: LightningIRDataModule
  init_args:
    num_workers: 1
    inference_batch_size: 4
    inference_datasets:
      - class_path: RunDataset
        init_args:
          run_path_or_id: runs/bm25/task2-collie-2025.run
          depth: 100
          sampling_strategy: top
model:
  class_path: CrossEncoderModule
  init_args:
    model_name_or_path: lightning_logs/version_6/huggingface_checkpoint
    evaluation_metrics:
    - P@1
    - R@1
    - nDCG@1
    - MAP@1
    - MRR@1