model:
  class_path: set_encoder.set_encoder.SetEncoderElectraModule
  init_args:
    model_name_or_path: google/electra-base-discriminator
    depth: 100
    other_doc_attention: true
    freeze_position_embeddings: true
    loss_function:
      class_path: LocalizedContrastive
      # class_path: RankNet
      init_args:
        reduction: mean
    compile_model: true
