model:
  class_path: set_encoder.set_encoder.SetEncoderElectraModule
  init_args:
    model_name_or_path: google/electra-base-discriminator
    # model_name_or_path: google/electra-large-discriminator
    repeat_linear_layer: false
    config:
      class_path: set_encoder.set_encoder.SetEncoderElectraConfig
      init_args:
        query_length: 32
        doc_length: 256
        depth: 100
        add_extra_token: false
        other_sequence_embedding: false
        sample_missing_docs: true
    loss_functions:
      - class_path: LocalizedContrastiveEstimation
      # - class_path: set_encoder.loss.RepeatCrossEntropyLoss
      # - class_path: set_encoder.loss.DuplicateAwareRankNet
