data:
  class_path: LightningIRDataModule
  init_args:
    num_workers: 1
    inference_batch_size: 4
    inference_datasets:
      - class_path: RunDataset
        init_args:
          run_path_or_id: ./runs/msmarco-passage-trec-dl-2019-judged.run
          depth: 100
          sample_size: 100
          sampling_strategy: top
      - class_path: RunDataset
        init_args:
          run_path_or_id: ./runs/msmarco-passage-trec-dl-2020-judged.run
          depth: 100
          sample_size: 100
          sampling_strategy: top
